org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
android.useAndroidX=true
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64
newArchEnabled=false
hermesEnabled=false
edgeToEdgeEnabled=false
android.suppressUnsupportedCompileSdk=36
org.gradle.daemon=true
systemProp.http.connectionTimeout=60000
systemProp.http.socketTimeout=60000